// <auto-generated />
using System;
using FoxCoinProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoxCoinProject.Migrations
{
    [DbContext(typeof(FoxBankContext))]
    partial class FoxBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoxCoinProject.Models.TransAction", b =>
                {
                    b.Property<long>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<long?>("FromUserUserId");

                    b.Property<long?>("ToUserUserId");

                    b.HasKey("TransId");

                    b.HasIndex("FromUserUserId");

                    b.HasIndex("ToUserUserId");

                    b.ToTable("TransActions");
                });

            modelBuilder.Entity("FoxCoinProject.Models.UserAccount", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("FoxCoinProject.Models.TransAction", b =>
                {
                    b.HasOne("FoxCoinProject.Models.UserAccount", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserUserId");

                    b.HasOne("FoxCoinProject.Models.UserAccount", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
